### ISSUE TITLE
Wrong default paths

### ISSUE THREAD

**Issue by alsa64** [ptrsuder/IEU.Winforms#1]
![1. warning](http://oi68.tinypic.com/24qp8if.jpg)
![2. warning](http://oi68.tinypic.com/28auveg.jpg)
Expected behaviour: Get paths from current path maybe (../esrgan/). Example:
```
somePath/
|-esrgan/
|-IEU/
```

**Comment by ptrsuder** [comment]
Custom setting file was included in release by mistake.
