### ISSUE TITLE
Tile merging issue

### ISSUE THREAD

**Issue by starkgate** [ptrsuder/IEU.Winforms#11]
I ran into a problem while running a batch of textures through a 1x denoise model. It only happened with one texture, although I don't see what's different about it. Doesn't happen anymore once I restart IEU and run "merge" again. Not sure what's going on or if you want to look into it, but here you go.

Tiles
![explorer_2019-09-10_20-20-13](https://user-images.githubusercontent.com/12874678/64639619-78060c80-d408-11e9-911c-a27c3e03113e.png)

Output
![i_view64_2019-09-10_20-20-31](https://user-images.githubusercontent.com/12874678/64639624-79cfd000-d408-11e9-92f9-b20988b32e8e.png)

Files
[LR.zip](https://github.com/ptrsuder/IEU.Winforms/files/3597178/LR.zip)

**Comment by ptrsuder** [comment]
Not sure what happened neither. I will close issue for now, but if this will happen again, please report!
