### ISSUE TITLE
Some weird problem when using x1 models

### ISSUE THREAD

**Issue by starkgate** [ptrsuder/IEU.Winforms#12]
It's me again with another obscure problem I'm having. Tried a few different pictures, but I always get this error when I use a x1 model like denoise BC1. Works perfectly fine with x4 models.

Edit: Tested on another computer, I can't reproduce the problem there. I tried reinstalling IEU, ESRGAN and torch, no change.

![ImageEnhancingUtility Winforms_2019-09-12_23-29-32](https://user-images.githubusercontent.com/12874678/64822407-35cdfe00-d5b5-11e9-9822-3c7aa72a15b7.png)

**Comment by ptrsuder** [comment]
Is this true for any x1 model or only for a specific one?

**Comment by starkgate** [comment]
Any x1 model

**Comment by starkgate** [comment]
https://stackoverflow.com/questions/53743498/keyerror-filename-storages-not-found

Well. I'm not sure what happened or why only x1 models were corrupted, but redownloading them fixed the problem. Could be good to manage the "corrupted model" exception with a nice error message
