### ISSUE TITLE
Process multiple images at once

### ISSUE THREAD

**Issue by starkgate** [ptrsuder/IEU.Winforms#14]
I have a very heterogeneous set of images I want to run, resolution goes from 64x64 to 1024x1024, and I was wondering if there was a way to speed things up by packing smaller images together.

Say I allowed tiles up to 1000x1000 in the settings, and I want to process 10 images that are 500x500. I assume it would be possible to have IEU process 4 at a time instead of one after the other as it does now ? Would it actually be faster ?

**Comment by ptrsuder** [comment]
Wouldn't be faster.
