### ISSUE TITLE
hi have this module not found issue idk how to fix the issue

### ISSUE THREAD

**Issue by cktan21** [ptrsuder/IEU.Winforms#18]
hi I am really really new to coding so I usually have no idea what's going on. I have run into an issue where they will have an error saying error module not found not module named 'architect' and i have no clue how to fix it after searching through online forums. PAny help will be appreciated thanksss

**Comment by ptrsuder** [comment]
Most likely you are using different ESRGAN version. You need the one from the link in Requirements.
