### ISSUE TITLE
Please add Anaconda environment selection [FEATURE]

### ISSUE THREAD

**Issue by TomArrow** [ptrsuder/IEU.Winforms#19]
**Is your feature request related to a problem? Please describe.**
The way I set up my python, the python installation with all the dependencies I need for ESRGAN always needs to be activated via "conda activate [environment name]" or, in a .bat script, like this: "call conda activate [environment name]". Without this, it will not work I think.

**Describe the solution you'd like**
Just a textbox to enter the conda environment name, if required, which is then called before the python script is executed so that the environment is correct.

**Describe alternatives you've considered**
None.

**Additional context**
That's it pretty much.

**Comment by ptrsuder** [comment]
Added in https://github.com/ptrsuder/IEU.Winforms/commit/6b88a013af67b8dd49d53e26361d864f59f33270 and https://github.com/ptrsuder/IEU.Core/commit/2de1eb87b0c31414798b9e1ecc23a4c2965c22b3
Can't test it as I don't have Anaconda ;)

**Comment by TomArrow** [comment]
Awesome, thanks. I'm currently running something on my GPU so can't test it in the coming days/weeks, but I'll let you know asap.

**Comment by WinkelCode** [comment]
I can confirm it works for the main functionality, unfortunately the preview feature doesn't honor the setting.

**Comment by ptrsuder** [comment]
Should be fixed in https://github.com/ptrsuder/IEU.Core/commit/10532d81954cfa421e769d7e94071f835f4f7752
