### ISSUE TITLE
[FEATURE] Add Support to run inputs sequentially 

### ISSUE THREAD

**Issue by Limeysoda1** [ptrsuder/IEU.Winforms#20]
[FEATURE] I would like IEU to be able to run inputs sequentially such as frames for a video, as of right now it sees the left most number and goes off of that which results in it going randomly down an input of frames. It would be very helpful to have the option to use the RIGHT most number to select order allowing it to run in numerical order.

**Comment by ptrsuder** [comment]
Added in https://github.com/ptrsuder/IEU.Core/commit/defa933eedd373c551b967b0a1960866797cbd48
