### ISSUE TITLE
[Bug] No tree view

### ISSUE THREAD

**Issue by BearLesbian** [ptrsuder/IEU.Winforms#21]
**Describe the bug**
I have a problem at my first launch. (Using version 0.10.4) After running [SPLIT] I don't get a tree view, from which I can choose models from. 
![shrthsrhr](https://user-images.githubusercontent.com/65361413/81965212-0413a800-9618-11ea-89c3-c4474e959209.png)

**Comment by ptrsuder** [comment]
You get tree view not from Split, but after setting folder paths in settings. Models folder should contain your models.
