### ISSUE TITLE
[BUG] Merging tiles takes very very long and takes up 30GB ram, sometimes errors

### ISSUE THREAD

**Issue by ProductiveAsparagus56** [ptrsuder/IEU.Winforms#22]
When trying to merge tiles it takes more than 10 minutes to process each image (720x4000), when i let it process a couple of images it takes up enough ram to make my pc almost crash (30GB), it sometimes errors with (extract area etc)

**To Reproduce**
1. try merging tiles, the bug will happen with random images

**Expected behavior**
merge tiles

**Version**
 - Version 0.10.04

**Comment by ptrsuder** [comment]
Try [dev-beta.3](https://github.com/ptrsuder/IEU.Winforms/releases/tag/dev-beta.3) please.

**Comment by ProductiveAsparagus56** [comment]
> 
> 
> Try [dev-beta.3](https://github.com/ptrsuder/IEU.Winforms/releases/tag/dev-beta.3) please.

i tried it but bitdefender flags it as a virus and i cant find a way around bitdefender, i know that its safe. just gotta find the thing that flags it as suspicious 🤔

**Comment by rawr51919** [comment]
just disable bitdefender or add the exe to bitdefender's exceptions list @Audition-CSBlock
