### ISSUE TITLE
"Attempted to divide by zero" when merging tiles w/ multiple models

### ISSUE THREAD

**Issue by AdamSkelecoot** [ptrsuder/IEU.Winforms#25]
**Describe the bug**
Whenever I try to use two models at the same time to upscale an image (so that I can easily compare the two results), the tiles do not merge. Instead, it prints out that it "attempted to divide by zero" and  skips both results.

**To Reproduce**
Using these settings:
![image](https://user-images.githubusercontent.com/69521008/89912871-f788f680-dbea-11ea-9c2e-75e8728afb23.png)
1. Select two models from the Basic tab (I chose Digipaint and Digital Frames, as the image is a screenshot from an animated film.)
2. Have the Output mode as "Folder for each image"
3. Go through the usual method ("Split", "Run ESRGAN", "Merge", or "Split-ESRGAN-Merge")

**Expected behavior**
The tiles should properly merge, resulting in two folders in the output folder, one for each model.

**Screenshots**
The error in question:
![Capture](https://user-images.githubusercontent.com/69521008/89913483-b04f3580-dbeb-11ea-9684-d5c4d8268f10.PNG)

**Version**
 - Version 0.11.0

**Additional notes**
I started having this problem as soon as I updated IEU. It's possible that the update messed something up somehow. In the meantime, I have to use each model one at a time to avoid the bug, and rename each image to differentiate between them.

**Comment by ptrsuder** [comment]
Yeah, sorry. This was already fixed in commits. Also I post my hotfixes on discord.

**Comment by ZirumAndBigBro** [comment]
Hi ptrsuder, thank you for your work. 
I have the same issue with current release. 
If you allready fixed this, can you please update the release files?

Thanks

**Comment by ptrsuder** [comment]
I created mega folder where I will post hotfixes between releases.

https://mega.nz/folder/Ss4iGILb#VC2O1hjYpjF9wOhkthF3Rw
