### ISSUE TITLE
Dividing with zero when merging [BUG]

### ISSUE THREAD

**Issue by GInnjo** [ptrsuder/IEU.Winforms#27]
If you set Resize above 1 (2 or 4) on Image preprocess' "Resize" setting:

      Merging image will divide with zero.
![image](https://user-images.githubusercontent.com/44971436/92267938-32303700-eeea-11ea-91c0-c303531f6dbf.png)

      Preview gives error: "Failed to create preview!" ( at the very end )
![image](https://user-images.githubusercontent.com/44971436/92268241-b2569c80-eeea-11ea-99e5-dce3bc84f976.png)

Settings:
![image](https://user-images.githubusercontent.com/44971436/92268139-81766780-eeea-11ea-8cfb-f72e1a4c8e0a.png)

**Comment by Cyber-Snake** [comment]
Have the save issue `Attempted to divide by zero.` ,except I get it even with default settings when I use multiple models.

**Comment by Cyber-Snake** [comment]
Updating to hotfix version from [here](https://github.com/ptrsuder/IEU.Winforms/issues/25) fixed the issue.
