### ISSUE TITLE
No error, IEU does not perform enhancement with RTX 3090 [BUG]

### ISSUE THREAD

**Issue by AaronHofer** [ptrsuder/IEU.Winforms#31]
Went form RTX 2080 TI to RTX 3090 on Windows 10. 8700K, 32GB RAM. On latest drivers 457.09 (tried 2 previous versions also).  

Hitting Preview or "enhance and save as png" etc does nothing, the progress bar animates and python runs in the background but GPU never allocates any memory usage and the task never completes.

**Comment by ptrsuder** [comment]
Can't say anything about that. Can you try using ESRGAN without IEU and see how it goes? 
https://github.com/JoeyBallentine/ESRGAN is a good fork.

**Comment by AaronHofer** [comment]
Just tried it, it does the same thing so the issue is with the script or something else with ESRGAN, Thanks. 

From doing some additional reading, it appears the problem is with pytorch, probably needs to be recompiled to support ampere.

Final edit: Got it to work by updating pytorch and torchvision to the current nightly versions.

pip uninstall torch torchvision
pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html

**Comment by ptrsuder** [comment]
Great to know!
