### ISSUE TITLE
[BUG] "Sequence contains no elements"

### ISSUE THREAD

**Issue by AdamSkelecoot** [ptrsuder/IEU.Winforms#34]
**Describe the bug**
While I can see that the program has successfully upscaled the tiles in the result folder, it is unable to merge said files because the "sequence contains no elements", even when just pressing the "Merge" button afterwards. I tried changing the filename of the original file (since it had +'s in it and I thought that might have caused issues), but that didn't seem to work. I also tried it with the "process with memory" option on, but not only did it not work, but the program also closed/crashed after throwing up the error message.

**To Reproduce**
What settings: See screenshots
1. Take a 1500x2500+ image and place it in "IEU_input"
2. Use Digipaint35000
2. Click on 'SPLIT-ESRGAN-MERGE'
3. Wait for tiles to render - they should appear in the results folder

**Expected behavior**
The program should merge the completed tiles after rendering them.

**Screenshots**
![image](https://user-images.githubusercontent.com/69521008/118560036-c680b800-b760-11eb-9769-2a75f782d210.png)
![image](https://user-images.githubusercontent.com/69521008/118560061-d39da700-b760-11eb-8f1c-304089ca6294.png)

**Version**
 - Version 0.11.0

**Comment by ptrsuder** [comment]
0.11 by now is outdated and full of bugs. I suggest trying 0.12 or another tool for now.

**Comment by AdamSkelecoot** [comment]
Couldn't find 0.12 for a moment, but I did eventually and downloaded that. It's now working now. Thanks!
